#!/bin/bash

IMAGE_DIR=$HEAT_DISSIPATION_CHAPEL/images/
APP=./heat_dissipation
ARGS=$*

N=8192
M=8192
T_TYPE=plasma
C_TYPE=pat2
I=500
E=0.01

T=$IMAGE_DIR$T_TYPE"_"$N"x"$M".pgm"
C=$IMAGE_DIR$C_TYPE"_"$N"x"$M".pgm"

export MPIRUN_CMD="mpirun --mca btl ^usnic -np %N %C"
#export MPIRUN_CMD="mpirun --mca btl ^usnic --map-by ppr:1:node --bind-to none --report-bindings -np %N %C"
#export CHPL_RT_NUM_THREADS_PER_LOCALE=16

$APP -v --N $N --M $M --T $T --C $C --I $I --E $E $ARGS
